// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtgHH9P8ah7SKU9RRKswkvZPv8XKmghYI',
    appId: '1:891428118066:web:d8adbb3d1982b257b9a62b',
    messagingSenderId: '891428118066',
    projectId: 'beats-8bec3',
    authDomain: 'beats-8bec3.firebaseapp.com',
    storageBucket: 'beats-8bec3.appspot.com',
    measurementId: 'G-WMXRYK8VFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjhjbbzmQALhs8WtbaPxxTlVKMthK-RM',
    appId: '1:891428118066:android:0e833aa1ef137ae0b9a62b',
    messagingSenderId: '891428118066',
    projectId: 'beats-8bec3',
    storageBucket: 'beats-8bec3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo6xHJ1oC93UZkrR2Djg3BoyblP1z7Z_4',
    appId: '1:891428118066:ios:18438cb831736144b9a62b',
    messagingSenderId: '891428118066',
    projectId: 'beats-8bec3',
    storageBucket: 'beats-8bec3.appspot.com',
    iosBundleId: 'com.example.musicProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo6xHJ1oC93UZkrR2Djg3BoyblP1z7Z_4',
    appId: '1:891428118066:ios:18438cb831736144b9a62b',
    messagingSenderId: '891428118066',
    projectId: 'beats-8bec3',
    storageBucket: 'beats-8bec3.appspot.com',
    iosBundleId: 'com.example.musicProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtgHH9P8ah7SKU9RRKswkvZPv8XKmghYI',
    appId: '1:891428118066:web:7c5811c24b616ac6b9a62b',
    messagingSenderId: '891428118066',
    projectId: 'beats-8bec3',
    authDomain: 'beats-8bec3.firebaseapp.com',
    storageBucket: 'beats-8bec3.appspot.com',
    measurementId: 'G-HSWRGDWZH7',
  );

}